# Generated by Django 5.0.1 on 2024-02-22 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='service',
            new_name='service1s',
        ),
    ]
