# Generated by Django 5.0.1 on 2024-02-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='ima',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
