# Generated by Django 5.0.1 on 2024-03-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_reviewp'),
    ]

    operations = [
        migrations.CreateModel(
            name='cservice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('email', models.EmailField(max_length=90)),
                ('subject', models.CharField(max_length=90)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
