# Generated by Django 5.0.1 on 2024-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_cservice_delete_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=90)),
                ('bemail', models.EmailField(max_length=90)),
                ('bdtime', models.DateTimeField(max_length=90)),
                ('bpeople', models.CharField(max_length=90)),
                ('brequest', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='reviewp',
        ),
    ]
