# Generated by Django 5.0.1 on 2024-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_bookings_delete_reviewp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='bdtime',
            field=models.CharField(max_length=90),
        ),
    ]
