# Generated by Django 5.0.1 on 2024-03-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_bookings_bdtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='bdtime',
            field=models.IntegerField(max_length=90),
        ),
    ]
