# Generated by Django 5.0.3 on 2024-04-06 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_post_student_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.student'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
