# Generated by Django 5.0.3 on 2024-04-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_alter_like_post_student_total_likes_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='atendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aname', models.CharField(max_length=90)),
                ('atten', models.IntegerField(default=0)),
            ],
        ),
    ]
